// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgvejltglycwihyjbxiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxndmVqbHRnbHljd2loeWpieGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjg3MjQsImV4cCI6MjA3NDY0NDcyNH0.lzsnpR7K03P0f-pl60z-TRK-dPsYIHEoY1gxS-AfHnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});