// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://przltphrifikahinvucz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByemx0cGhyaWZpa2FoaW52dWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTgyOTQsImV4cCI6MjA3MzY3NDI5NH0.qNGHf3be7hQ_Sia4rzTzuVRdljKcnvbrbAcaSLPRzFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});